export const Actions = {
    APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
    SET_CONTENT_OF_CONFIRM_MODAL: 'SET_CONTENT_OF_CONFIRM_MODAL',


    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAIL: 'USER_LOGIN_FAIL',
    PROCESS_LOGOUT: 'PROCESS_LOGOUT',
    UPDATE_USER: 'UPDATE_USER',

    GET_MAJOR: 'GET_MAJOR',
    ADD_MAJOR: 'ADD_MAJOR',
    DELETE_MAJOR: 'DELETE_MAJOR',
    EDIT_MAJOR: 'EDIT_MAJOR'
}